<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

/*
 * This file is part of the `gata` project.
 *
 * (c) Aula de Software Libre de la UCO <aulasoftwarelibre@uco.es>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace AulaSoftwareLibre\Gata\Domain\Idea\Model;

final class IdeaDescription
{
    private $value;

    public function __construct(string $value)
    {
        $this->value = $value;
    }

    public function value(): string
    {
        return $this->value;
    }

    public function toString(): string
    {
        return $this->value;
    }

    public function __toString(): string
    {
        return $this->value;
    }

    public static function fromString(string $ideaDescription): IdeaDescription
    {
        return new self($ideaDescription);
    }

    public function equals(IdeaDescription $ideaDescription): bool
    {
        if (\get_class($this) !== \get_class($ideaDescription)) {
            return false;
        }

        return $this->value === $ideaDescription->value;
    }
}
