<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

/*
 * This file is part of the `gata` project.
 *
 * (c) Aula de Software Libre de la UCO <aulasoftwarelibre@uco.es>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace AulaSoftwareLibre\Gata\Domain\Idea\Event;

final class IdeaWasRetitled extends \Prooph\EventSourcing\AggregateChanged
{
    public const MESSAGE_NAME = 'AulaSoftwareLibre\Gata\Domain\Idea\Event\IdeaWasRetitled';

    protected $messageName = self::MESSAGE_NAME;

    protected $payload = [];

    private $ideaId;
    private $title;

    public function ideaId(): \AulaSoftwareLibre\Gata\Domain\Idea\Model\IdeaId
    {
        if (null === $this->ideaId) {
            $this->ideaId = \AulaSoftwareLibre\Gata\Domain\Idea\Model\IdeaId::fromString($this->aggregateId());
        }

        return $this->ideaId;
    }

    public function title(): \AulaSoftwareLibre\Gata\Domain\Idea\Model\IdeaTitle
    {
        if (null === $this->title) {
            $this->title = \AulaSoftwareLibre\Gata\Domain\Idea\Model\IdeaTitle::fromString($this->payload['title']);
        }

        return $this->title;
    }

    public static function with(\AulaSoftwareLibre\Gata\Domain\Idea\Model\IdeaId $ideaId, \AulaSoftwareLibre\Gata\Domain\Idea\Model\IdeaTitle $title): IdeaWasRetitled
    {
        return new self($ideaId->toString(), [
            'title' => $title->toString(),
        ]);
    }

    protected function setPayload(array $payload): void
    {
        if (!isset($payload['title']) || !\is_string($payload['title'])) {
            throw new \InvalidArgumentException("Key 'title' is missing in payload or is not a string");
        }

        $this->payload = $payload;
    }
}
