<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

/*
 * This file is part of the `gata` project.
 *
 * (c) Aula de Software Libre de la UCO <aulasoftwarelibre@uco.es>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace AulaSoftwareLibre\Gata\Domain\Idea\Event;

final class IdeaWasAdded extends \Prooph\EventSourcing\AggregateChanged
{
    public const MESSAGE_NAME = 'AulaSoftwareLibre\Gata\Domain\Idea\Event\IdeaWasAdded';

    protected $messageName = self::MESSAGE_NAME;

    protected $payload = [];

    private $ideaId;
    private $groupId;
    private $title;
    private $description;

    public function ideaId(): \AulaSoftwareLibre\Gata\Domain\Idea\Model\IdeaId
    {
        if (null === $this->ideaId) {
            $this->ideaId = \AulaSoftwareLibre\Gata\Domain\Idea\Model\IdeaId::fromString($this->aggregateId());
        }

        return $this->ideaId;
    }

    public function groupId(): \AulaSoftwareLibre\Gata\Domain\Group\Model\GroupId
    {
        if (null === $this->groupId) {
            $this->groupId = \AulaSoftwareLibre\Gata\Domain\Group\Model\GroupId::fromString($this->payload['groupId']);
        }

        return $this->groupId;
    }

    public function title(): \AulaSoftwareLibre\Gata\Domain\Idea\Model\IdeaTitle
    {
        if (null === $this->title) {
            $this->title = \AulaSoftwareLibre\Gata\Domain\Idea\Model\IdeaTitle::fromString($this->payload['title']);
        }

        return $this->title;
    }

    public function description(): \AulaSoftwareLibre\Gata\Domain\Idea\Model\IdeaDescription
    {
        if (null === $this->description) {
            $this->description = \AulaSoftwareLibre\Gata\Domain\Idea\Model\IdeaDescription::fromString($this->payload['description']);
        }

        return $this->description;
    }

    public static function with(\AulaSoftwareLibre\Gata\Domain\Idea\Model\IdeaId $ideaId, \AulaSoftwareLibre\Gata\Domain\Group\Model\GroupId $groupId, \AulaSoftwareLibre\Gata\Domain\Idea\Model\IdeaTitle $title, \AulaSoftwareLibre\Gata\Domain\Idea\Model\IdeaDescription $description): IdeaWasAdded
    {
        return new self($ideaId->toString(), [
            'groupId' => $groupId->toString(),
            'title' => $title->toString(),
            'description' => $description->toString(),
        ]);
    }

    protected function setPayload(array $payload): void
    {
        if (!isset($payload['groupId']) || !\is_string($payload['groupId'])) {
            throw new \InvalidArgumentException("Key 'groupId' is missing in payload or is not a string");
        }

        if (!isset($payload['title']) || !\is_string($payload['title'])) {
            throw new \InvalidArgumentException("Key 'title' is missing in payload or is not a string");
        }

        if (!isset($payload['description']) || !\is_string($payload['description'])) {
            throw new \InvalidArgumentException("Key 'description' is missing in payload or is not a string");
        }

        $this->payload = $payload;
    }
}
