<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

/*
 * This file is part of the `gata` project.
 *
 * (c) Aula de Software Libre de la UCO <aulasoftwarelibre@uco.es>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace AulaSoftwareLibre\Gata\Domain\Idea\Event;

final class IdeaAttendeeWasUnregistered extends \Prooph\EventSourcing\AggregateChanged
{
    public const MESSAGE_NAME = 'AulaSoftwareLibre\Gata\Domain\Idea\Event\IdeaAttendeeWasUnregistered';

    protected $messageName = self::MESSAGE_NAME;

    protected $payload = [];

    private $ideaId;
    private $userId;

    public function ideaId(): \AulaSoftwareLibre\Gata\Domain\Idea\Model\IdeaId
    {
        if (null === $this->ideaId) {
            $this->ideaId = \AulaSoftwareLibre\Gata\Domain\Idea\Model\IdeaId::fromString($this->aggregateId());
        }

        return $this->ideaId;
    }

    public function userId(): \AulaSoftwareLibre\Gata\Domain\User\Model\UserId
    {
        if (null === $this->userId) {
            $this->userId = \AulaSoftwareLibre\Gata\Domain\User\Model\UserId::fromString($this->payload['userId']);
        }

        return $this->userId;
    }

    public static function with(\AulaSoftwareLibre\Gata\Domain\Idea\Model\IdeaId $ideaId, \AulaSoftwareLibre\Gata\Domain\User\Model\UserId $userId): IdeaAttendeeWasUnregistered
    {
        return new self($ideaId->toString(), [
            'userId' => $userId->toString(),
        ]);
    }

    protected function setPayload(array $payload): void
    {
        if (!isset($payload['userId']) || !\is_string($payload['userId'])) {
            throw new \InvalidArgumentException("Key 'userId' is missing in payload or is not a string");
        }

        $this->payload = $payload;
    }
}
