<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

/*
 * This file is part of the `gata` project.
 *
 * (c) Aula de Software Libre de la UCO <aulasoftwarelibre@uco.es>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace AulaSoftwareLibre\Gata\Domain\Group\Event;

final class GroupWasRenamed extends \Prooph\EventSourcing\AggregateChanged
{
    public const MESSAGE_NAME = 'AulaSoftwareLibre\Gata\Domain\Group\Event\GroupWasRenamed';

    protected $messageName = self::MESSAGE_NAME;

    protected $payload = [];

    private $groupId;
    private $name;

    public function groupId(): \AulaSoftwareLibre\Gata\Domain\Group\Model\GroupId
    {
        if (null === $this->groupId) {
            $this->groupId = \AulaSoftwareLibre\Gata\Domain\Group\Model\GroupId::fromString($this->aggregateId());
        }

        return $this->groupId;
    }

    public function name(): \AulaSoftwareLibre\Gata\Domain\Group\Model\GroupName
    {
        if (null === $this->name) {
            $this->name = \AulaSoftwareLibre\Gata\Domain\Group\Model\GroupName::fromString($this->payload['name']);
        }

        return $this->name;
    }

    public static function with(\AulaSoftwareLibre\Gata\Domain\Group\Model\GroupId $groupId, \AulaSoftwareLibre\Gata\Domain\Group\Model\GroupName $name): GroupWasRenamed
    {
        return new self($groupId->toString(), [
            'name' => $name->toString(),
        ]);
    }

    protected function setPayload(array $payload): void
    {
        if (!isset($payload['name']) || !\is_string($payload['name'])) {
            throw new \InvalidArgumentException("Key 'name' is missing in payload or is not a string");
        }

        $this->payload = $payload;
    }
}
